# Databricks notebook source
# MAGIC %md
# MAGIC # Bronze API Ingestion — Samsara Fleet
# MAGIC
# MAGIC This notebook is auto-generated by Bitool's Pipeline Builder.
# MAGIC It fetches data from the Samsara API and writes raw records to Bronze Delta tables.
# MAGIC
# MAGIC **Deployment model**: Runs as a Databricks Job on a schedule.
# MAGIC **Ops integration**: Calls back to Bitool after each run to update freshness status.

# COMMAND ----------

# Widget parameters (set by Databricks Job or manually)
dbutils.widgets.text("api_base_url", "https://api.samsara.com", "API Base URL")
dbutils.widgets.text("api_token_secret", "samsara-api-token", "Databricks Secret Name")
dbutils.widgets.text("secret_scope", "bitool", "Secret Scope")
dbutils.widgets.text("catalog", "main", "Unity Catalog")
dbutils.widgets.text("bronze_schema", "bronze", "Bronze Schema")
dbutils.widgets.text("endpoints", "fleet/vehicles,fleet/drivers", "Endpoints (comma-separated)")
dbutils.widgets.text("bitool_callback_url", "", "Bitool Callback URL (optional)")
dbutils.widgets.text("bitool_callback_token_secret", "", "Bitool Callback Token Secret (optional)")
dbutils.widgets.text("bitool_callback_token", "", "Bitool Callback Token (optional)")
dbutils.widgets.text("graph_id", "", "Bitool Graph ID")
dbutils.widgets.text("api_node_id", "", "Bitool API Node ID")
dbutils.widgets.text("endpoint_name", "", "Bitool Endpoint Name (optional)")
dbutils.widgets.text("source_system", "samsara", "Source System Name")
dbutils.widgets.text("endpoint_configs_json", "", "Endpoint configs JSON (optional)")

# COMMAND ----------

import requests
import json
import hashlib
from datetime import datetime, timezone
from pyspark.sql import Row
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DateType
from requests.adapters import HTTPAdapter

# Configuration
API_BASE_URL = dbutils.widgets.get("api_base_url")
SECRET_SCOPE = dbutils.widgets.get("secret_scope")
API_TOKEN_SECRET = dbutils.widgets.get("api_token_secret")
CATALOG = dbutils.widgets.get("catalog")
BRONZE_SCHEMA = dbutils.widgets.get("bronze_schema")
ENDPOINTS = [e.strip() for e in dbutils.widgets.get("endpoints").split(",") if e.strip()]
BITOOL_CALLBACK = dbutils.widgets.get("bitool_callback_url")
BITOOL_CALLBACK_TOKEN_SECRET = dbutils.widgets.get("bitool_callback_token_secret")
BITOOL_CALLBACK_TOKEN = dbutils.widgets.get("bitool_callback_token")
GRAPH_ID = dbutils.widgets.get("graph_id")
API_NODE_ID = dbutils.widgets.get("api_node_id")
ENDPOINT_NAME = dbutils.widgets.get("endpoint_name")
SOURCE_SYSTEM = dbutils.widgets.get("source_system")
ENDPOINT_CONFIGS_JSON = dbutils.widgets.get("endpoint_configs_json")

# Get API token from Databricks secrets
try:
    API_TOKEN = dbutils.secrets.get(scope=SECRET_SCOPE, key=API_TOKEN_SECRET)
except Exception:
    # Fallback: try environment variable
    import os
    API_TOKEN = os.environ.get("SAMSARA_API_TOKEN", os.environ.get("DATABRICKS_PAT", ""))

if not BITOOL_CALLBACK_TOKEN:
    try:
        BITOOL_CALLBACK_TOKEN = dbutils.secrets.get(scope=SECRET_SCOPE, key=BITOOL_CALLBACK_TOKEN_SECRET) if BITOOL_CALLBACK_TOKEN_SECRET else ""
    except Exception:
        import os
        BITOOL_CALLBACK_TOKEN = os.environ.get("BITOOL_CALLBACK_TOKEN", "")

print(f"Config: {len(ENDPOINTS)} endpoints, catalog={CATALOG}, schema={BRONZE_SCHEMA}")

HTTP = requests.Session()
HTTP.mount("https://", HTTPAdapter(pool_connections=8, pool_maxsize=8, max_retries=0))
HTTP.mount("http://", HTTPAdapter(pool_connections=8, pool_maxsize=8, max_retries=0))

API_CONNECT_TIMEOUT = 5
API_READ_TIMEOUT = 20
CONTROL_PLANE_CONNECT_TIMEOUT = 5
CONTROL_PLANE_READ_TIMEOUT = 10

# COMMAND ----------

# MAGIC %md
# MAGIC ## Bronze Schema Definition

# COMMAND ----------

BRONZE_SCHEMA_DEF = StructType([
    StructField("ingestion_id", StringType(), False),
    StructField("run_id", StringType(), False),
    StructField("batch_id", StringType(), False),
    StructField("source_system", StringType(), False),
    StructField("endpoint_name", StringType(), False),
    StructField("extracted_at_utc", StringType(), False),
    StructField("ingested_at_utc", StringType(), False),
    StructField("api_request_url", StringType(), True),
    StructField("api_page_number", IntegerType(), True),
    StructField("api_cursor", StringType(), True),
    StructField("http_status_code", IntegerType(), True),
    StructField("record_hash", StringType(), True),
    StructField("source_record_id", StringType(), True),
    StructField("event_time_utc", StringType(), True),
    StructField("partition_date", DateType(), True),
    StructField("load_date", DateType(), True),
    StructField("payload_json", StringType(), True),
])

# COMMAND ----------

# MAGIC %md
# MAGIC ## API Fetch + Bronze Write

# COMMAND ----------

import uuid
from datetime import date

def sha256(s):
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

def bitool_headers():
    headers = {}
    if BITOOL_CALLBACK_TOKEN:
        headers["X-Bitool-Callback-Token"] = BITOOL_CALLBACK_TOKEN
    return headers

def load_bootstrap():
    if not (BITOOL_CALLBACK and GRAPH_ID and API_NODE_ID):
        return None
    payload = {"graph_id": int(GRAPH_ID), "api_node_id": int(API_NODE_ID)}
    if ENDPOINT_NAME:
        payload["endpoint_name"] = ENDPOINT_NAME
    resp = requests.post(
        f"{BITOOL_CALLBACK}/ops/pipeline/bronzeBootstrap",
        json=payload,
        headers=bitool_headers(),
        timeout=(CONTROL_PLANE_CONNECT_TIMEOUT, CONTROL_PLANE_READ_TIMEOUT),
    )
    resp.raise_for_status()
    return resp.json()

def endpoint_configs_from_bootstrap(bootstrap):
    if ENDPOINT_CONFIGS_JSON:
        try:
            return json.loads(ENDPOINT_CONFIGS_JSON)
        except Exception as e:
            raise Exception(f"Invalid endpoint_configs_json: {e}")
    if bootstrap and bootstrap.get("endpoints"):
        return bootstrap["endpoints"]
    return [
        {
            "endpoint_name": endpoint,
            "endpoint_url": f"/{endpoint}" if not endpoint.startswith("/") else endpoint,
            "http_method": "GET",
            "pagination_strategy": "cursor",
            "cursor_param": "after",
            "cursor_field": "endCursor",
            "watermark_column": "updatedAtTime",
            "time_param": "updated_since",
            "json_explode_rules": [{"path": "data"}],
            "primary_key_fields": ["id"],
            "target_table": f"{CATALOG}.{BRONZE_SCHEMA}.{SOURCE_SYSTEM}_{endpoint.replace('/', '_')}_raw",
            "checkpoint": None,
            "query_params": {},
            "body_params": {},
            "request_headers": {},
            "page_size": 100,
        }
        for endpoint in ENDPOINTS
    ]

BOOTSTRAP = load_bootstrap()
if BOOTSTRAP:
    SOURCE_SYSTEM = BOOTSTRAP.get("source_system", SOURCE_SYSTEM)
    API_BASE_URL = BOOTSTRAP.get("api_base_url", API_BASE_URL)

ENDPOINT_CONFIGS = endpoint_configs_from_bootstrap(BOOTSTRAP)

def request_url(endpoint_cfg):
    endpoint_url = endpoint_cfg.get("endpoint_url") or endpoint_cfg.get("endpoint_name")
    return f"{API_BASE_URL.rstrip('/')}/{str(endpoint_url).lstrip('/')}"

def fetch_api_page(endpoint_cfg, cursor=None, watermark_start=None):
    """Fetch one page from the Samsara API."""
    url = request_url(endpoint_cfg)
    headers = {"Authorization": f"Bearer {API_TOKEN}"}
    headers.update(endpoint_cfg.get("request_headers") or {})
    params = dict(endpoint_cfg.get("query_params") or {})
    body = dict(endpoint_cfg.get("body_params") or {})
    method = str(endpoint_cfg.get("http_method") or "GET").upper()
    page_size = endpoint_cfg.get("page_size")
    if page_size and endpoint_cfg.get("pagination_strategy") in ("cursor", "offset", "page"):
        params.setdefault(endpoint_cfg.get("size_param") or "limit", page_size)
    if cursor:
        params[endpoint_cfg.get("cursor_param") or "after"] = cursor
    if watermark_start:
        params[endpoint_cfg.get("watermark_param") or endpoint_cfg.get("time_param") or endpoint_cfg.get("watermark_column") or "updated_since"] = watermark_start

    resp = HTTP.request(
        method,
        url,
        headers=headers,
        params=params,
        json=body if method != "GET" else None,
        timeout=(API_CONNECT_TIMEOUT, API_READ_TIMEOUT),
    )
    resp.raise_for_status()
    return resp.json(), resp.status_code

def extract_records(body, explode_path="data"):
    """Extract individual records from API response."""
    data = body
    if explode_path:
        normalized = str(explode_path).replace("$.", "").replace("[]", "")
        for segment in [s for s in normalized.split(".") if s]:
            if isinstance(data, dict):
                data = data.get(segment)
            else:
                data = None
                break
    if isinstance(data, list):
        return data
    return [data] if data else []

def get_watermark(record, watermark_field="updatedAtTime"):
    """Extract watermark value from a record."""
    if not isinstance(record, dict):
        return None
    return record.get(watermark_field) or record.get("time") or record.get("startTime")

def get_record_id(record, key_field="id"):
    """Extract primary key from a record."""
    if not isinstance(record, dict):
        return ""
    return str(record.get(key_field, ""))

def ingest_endpoint(endpoint_cfg, run_id):
    """Fetch all pages for an endpoint and return Bronze rows."""
    now = datetime.now(timezone.utc)
    now_str = now.isoformat()
    today = date.today()
    endpoint_name = endpoint_cfg["endpoint_name"]
    checkpoint = endpoint_cfg.get("checkpoint") or {}
    watermark_start = checkpoint.get("last_successful_watermark")
    explode_path = None
    if endpoint_cfg.get("json_explode_rules"):
        explode_path = endpoint_cfg["json_explode_rules"][0].get("path")
    watermark_field = endpoint_cfg.get("watermark_column") or endpoint_cfg.get("time_field") or "updatedAtTime"
    primary_key_fields = endpoint_cfg.get("primary_key_fields") or ["id"]

    rows = []
    page_num = 0
    cursor = checkpoint.get("last_successful_cursor")
    has_next = True
    max_watermark = None

    while has_next:
        page_num += 1
        body, status_code = fetch_api_page(endpoint_cfg, cursor=cursor, watermark_start=watermark_start)
        records = extract_records(body, explode_path=explode_path)

        # Pagination
        pagination = body.get("pagination", {})
        has_next = pagination.get("hasNextPage", False)
        cursor = pagination.get("endCursor")

        batch_id = f"{run_id}-b{page_num:06d}"

        for record in records:
            payload_json = json.dumps(record, default=str)
            record_watermark = get_watermark(record, watermark_field=watermark_field)
            if record_watermark and (not max_watermark or str(record_watermark) > str(max_watermark)):
                max_watermark = str(record_watermark)
            rows.append(Row(
                ingestion_id=run_id,
                run_id=run_id,
                batch_id=batch_id,
                source_system=SOURCE_SYSTEM,
                endpoint_name=endpoint_name,
                extracted_at_utc=now_str,
                ingested_at_utc=now_str,
                api_request_url=request_url(endpoint_cfg),
                api_page_number=page_num,
                api_cursor=cursor,
                http_status_code=status_code,
                record_hash=sha256(payload_json),
                source_record_id=get_record_id(record, key_field=primary_key_fields[0]),
                event_time_utc=record_watermark,
                partition_date=today,
                load_date=today,
                payload_json=payload_json,
            ))

        print(f"  Page {page_num}: {len(records)} records, hasNext={has_next}")

        if page_num > 100:  # Safety limit
            print("  WARNING: Hit 100-page safety limit")
            break

    return rows, page_num, max_watermark, cursor

# COMMAND ----------

# MAGIC %md
# MAGIC ## Main Ingestion Loop

# COMMAND ----------

results = []

for endpoint_cfg in ENDPOINT_CONFIGS:
    run_id = str(uuid.uuid4())
    endpoint_name = endpoint_cfg["endpoint_name"]
    table_name = endpoint_cfg.get("target_table") or f"{CATALOG}.{BRONZE_SCHEMA}.{SOURCE_SYSTEM}_{endpoint_name.replace('/', '_')}_raw"
    started_at_utc = datetime.now(timezone.utc).isoformat()

    print(f"\n=== Ingesting {endpoint_name} -> {table_name} ===")
    print(f"  Run ID: {run_id}")

    try:
        rows, pages, max_watermark, next_cursor = ingest_endpoint(endpoint_cfg, run_id)

        if rows:
            df = spark.createDataFrame(rows, schema=BRONZE_SCHEMA_DEF)

            # Create schema if not exists
            spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{BRONZE_SCHEMA}")

            # Write to Delta (append mode, partitioned by partition_date)
            df.write \
                .format("delta") \
                .mode("append") \
                .partitionBy("partition_date") \
                .option("mergeSchema", "true") \
                .saveAsTable(table_name)

            print(f"  SUCCESS: {len(rows)} rows written to {table_name}")
        else:
            print(f"  No records returned from API")

        results.append({
            "endpoint": endpoint_name,
            "endpoint_name": endpoint_name,
            "table": table_name,
            "target_table": table_name,
            "run_id": run_id,
            "started_at_utc": started_at_utc,
            "rows_written": len(rows),
            "rows_extracted": len(rows),
            "pages_fetched": pages,
            "max_watermark": max_watermark,
            "next_cursor": next_cursor,
            "status": "success",
            "batch_id": f"{run_id}-b000001",
            "batch_seq": 1,
            "manifests": [{
                "batch_id": f"{run_id}-b000001",
                "batch_seq": 1,
                "status": "committed",
                "row_count": len(rows),
                "page_count": pages,
                "max_watermark": max_watermark,
                "next_cursor": next_cursor,
                "started_at_utc": started_at_utc,
                "committed_at_utc": datetime.now(timezone.utc).isoformat(),
            }],
        })

    except Exception as e:
        print(f"  FAILED: {str(e)}")
        results.append({
            "endpoint": endpoint_name,
            "endpoint_name": endpoint_name,
            "table": table_name,
            "target_table": table_name,
            "run_id": run_id,
            "started_at_utc": started_at_utc,
            "rows_written": 0,
            "rows_extracted": 0,
            "pages_fetched": 0,
            "status": "failed",
            "error": str(e),
            "batch_id": f"{run_id}-b000001",
            "batch_seq": 1,
        })

# COMMAND ----------

# MAGIC %md
# MAGIC ## Results Summary

# COMMAND ----------

for r in results:
    status_icon = "OK" if r["status"] == "success" else "FAIL"
    print(f"  [{status_icon}] {r['endpoint']}: {r['rows_written']} rows, {r['pages_fetched']} pages -> {r['table']}")

total_rows = sum(r["rows_written"] for r in results)
total_failed = sum(1 for r in results if r["status"] == "failed")
print(f"\nTotal: {total_rows} rows across {len(results)} endpoints, {total_failed} failed")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Callback to Bitool (Optional)

# COMMAND ----------

if BITOOL_CALLBACK:
    try:
        callback_payload = {
            "graph_id": int(GRAPH_ID) if GRAPH_ID else None,
            "api_node_id": int(API_NODE_ID) if API_NODE_ID else None,
            "source_system": SOURCE_SYSTEM,
            "results": results,
            "total_rows": total_rows,
            "total_failed": total_failed,
            "completed_at_utc": datetime.now(timezone.utc).isoformat(),
        }
        resp = requests.post(
            f"{BITOOL_CALLBACK}/ops/pipeline/bronzeCallback",
            json=callback_payload,
            headers=bitool_headers(),
            timeout=(CONTROL_PLANE_CONNECT_TIMEOUT, CONTROL_PLANE_READ_TIMEOUT),
        )
        print(f"Callback to Bitool: {resp.status_code}")
    except Exception as e:
        print(f"Callback failed (non-fatal): {e}")
else:
    print("No Bitool callback URL configured — skipping ops notification")

# COMMAND ----------

# Return results for Databricks job tracking
dbutils.notebook.exit(json.dumps({
    "status": "completed",
    "source_system": SOURCE_SYSTEM,
    "total_rows": total_rows,
    "total_failed": total_failed,
    "results": results,
}))
